import { CalendarDays, Search, Target, TrendingUp, X } from 'lucide-react'
import { useState } from 'react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { classifyCard, summaryFor } from '../lib/study'
import type { StoredCard, StudySession, WordEntry, WordLibrary } from '../types'

export function StatsView({ sessions, cards, words, libraries }: { sessions: StudySession[]; cards: StoredCard[]; words: WordEntry[]; libraries: WordLibrary[] }) {
  const [selectedWord, setSelectedWord] = useState<WordEntry>()
  const [wordSearch, setWordSearch] = useState('')
  const completed = sessions.filter((session) => session.status === 'completed')
  const summaries = completed.map((session) => ({ session, summary: summaryFor(session) }))
  const chartData = summaries.slice(-10).map(({ session, summary }) => ({ date: new Date(session.completedAt!).toLocaleDateString('zh-CN', { month: 'numeric', day: 'numeric' }), 首次记忆率: Math.round(summary.firstRecallRate * 100), 最终掌握率: Math.round(summary.finalMasteryRate * 100) }))
  const cardMap = new Map(cards.map((card) => [card.wordId, card]))
  const learnedWords = words.filter((word) => cardMap.has(word.id))
  const learned = learnedWords.length
  const dueCount = learnedWords.filter((word) => new Date(cardMap.get(word.id)!.card.due) <= new Date()).length
  const weakWords = words.filter((word) => ['待复习', '薄弱'].includes(classifyCard(cardMap.get(word.id)))).sort((a, b) => {
    const aCard = cardMap.get(a.id)!
    const bCard = cardMap.get(b.id)!
    return new Date(aCard.card.due).getTime() - new Date(bCard.card.due).getTime() || bCard.card.difficulty - aCard.card.difficulty
  }).slice(0, 12)
  const visibleLearned = learnedWords.filter((word) => !wordSearch || `${word.word} ${word.meaning}`.toLowerCase().includes(wordSearch.toLowerCase())).slice(0, 100)
  const selectedCard = selectedWord ? cardMap.get(selectedWord.id) : undefined
  const selectedHistory = selectedWord ? completed.filter((session) => session.wordIds.includes(selectedWord.id)).slice().reverse().slice(0, 10) : []
  const ratingLabel = { remembered: '记得', fuzzy: '模糊', forgotten: '忘记' }
  return <div className="page-content"><div className="page-heading"><p className="eyebrow">学习统计</p><h1>看见记忆的变化</h1><p>短期回忆和长期排程分开记录，不会因一轮内重复作答而虚高。</p></div>
    <div className="metric-grid"><div className="metric"><Target /><span>已学习词汇</span><strong>{learned}</strong></div><div className="metric"><CalendarDays /><span>今日待复习</span><strong>{dueCount}</strong></div><div className="metric"><TrendingUp /><span>已完成轮次</span><strong>{completed.length}</strong></div></div>
    <div className="stats-grid"><section className="panel chart-panel"><div className="section-heading"><div><h2>记忆率趋势</h2><p>最近10次完成的学习</p></div></div>{chartData.length ? <ResponsiveContainer width="100%" height={280}><BarChart data={chartData}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e4e1da" /><XAxis dataKey="date" tickLine={false} axisLine={false} /><YAxis domain={[0, 100]} tickLine={false} axisLine={false} unit="%" /><Tooltip /><Bar dataKey="首次记忆率" fill="#9da9a2" radius={[3,3,0,0]} /><Bar dataKey="最终掌握率" fill="#d36b45" radius={[3,3,0,0]} /></BarChart></ResponsiveContainer> : <div className="empty-state">完成第一轮学习后，这里会出现趋势图。</div>}</section>
      <section className="panel"><div className="section-heading"><div><h2>词库进度</h2><p>每次只专注一个词库</p></div></div><div className="progress-list">{libraries.map((library) => { const count = words.filter((word) => word.libraryId === library.id && cardMap.has(word.id)).length; const percent = library.wordCount ? count / library.wordCount * 100 : 0; return <div key={library.id}><span><strong>{library.name}</strong><small>{count}/{library.wordCount}</small></span><div className="progress-track"><i style={{width: `${percent}%`}} /></div></div> })}</div></section>
    </div>
    <section className="panel history-panel"><div className="section-heading"><div><h2>历史记录</h2><p>每轮原始表现都会保留</p></div></div>{summaries.length ? <div className="history-list">{summaries.slice().reverse().map(({session, summary}) => <div className="history-row" key={session.id}><span><strong>{session.libraryName}</strong><small>{new Date(session.completedAt!).toLocaleString('zh-CN')}</small></span><span>{summary.totalWords}词</span><span>首次 {Math.round(summary.firstRecallRate*100)}%</span><span>最终 {Math.round(summary.finalMasteryRate*100)}%</span></div>)}</div> : <div className="empty-state compact">暂无完成记录</div>}</section>
    <section className="panel"><div className="section-heading"><div><h2>薄弱词</h2><p>按到期时间和难度排序</p></div></div><div className="weak-word-grid">{weakWords.map((word) => <button key={word.id} onClick={() => setSelectedWord(word)}><strong>{word.word}</strong><span>{word.meaning}</span><small>{classifyCard(cardMap.get(word.id))} · {new Date(cardMap.get(word.id)!.card.due).toLocaleDateString('zh-CN')}</small></button>)}{!weakWords.length && <div className="empty-state compact">暂无薄弱词</div>}</div></section>
    <section className="panel learned-words-panel"><div className="section-heading"><div><h2>已学单词</h2><p>点击查看历次表现和下次复习时间</p></div></div><label className="search-box"><Search size={17} /><input value={wordSearch} onChange={(event) => setWordSearch(event.target.value)} placeholder="搜索已学单词或释义" /></label><div className="learned-word-list">{visibleLearned.map((word) => <button key={word.id} onClick={() => setSelectedWord(word)}><strong>{word.word}</strong><span>{classifyCard(cardMap.get(word.id))}</span><small>{new Date(cardMap.get(word.id)!.card.due).toLocaleDateString('zh-CN')}</small></button>)}{!visibleLearned.length && <div className="empty-state compact">没有匹配的已学单词</div>}</div>{learnedWords.length > 100 && !wordSearch && <p className="field-help">当前先显示 100 个单词，可通过搜索查找其他单词。</p>}</section>
    {selectedWord && selectedCard && <div className="modal-backdrop"><section className="modal word-detail-modal" role="dialog" aria-modal="true"><button className="icon-button modal-close" onClick={() => setSelectedWord(undefined)} aria-label="关闭单词详情"><X /></button><p className="eyebrow">单词详情</p><h2>{selectedWord.word}</h2><p className="phonetic detail-phonetic">{selectedWord.phonetic || '暂无音标'} · {selectedWord.partOfSpeech || '词性未标注'}</p><p className="meaning compact">{selectedWord.meaning}</p><dl className="word-schedule"><div><dt>当前状态</dt><dd>{classifyCard(selectedCard)}</dd></div><div><dt>下次复习</dt><dd>{new Date(selectedCard.card.due).toLocaleString('zh-CN')}</dd></div><div><dt>难度</dt><dd>{selectedCard.card.difficulty.toFixed(1)}</dd></div><div><dt>稳定性</dt><dd>{selectedCard.card.stability.toFixed(1)} 天</dd></div></dl><h3>最近学习记录</h3><div className="word-history">{selectedHistory.map((session) => { const events = session.events.filter((event) => event.wordId === selectedWord.id); return <div key={session.id}><span>{new Date(session.completedAt!).toLocaleDateString('zh-CN')}</span><strong>{events.length ? events.map((event) => ratingLabel[event.rating]).join(' → ') : session.spellingForgottenWordIds.includes(selectedWord.id) ? '拼写时忘记' : '完成'}</strong></div> })}{!selectedHistory.length && <p className="muted small">暂无历史明细</p>}</div></section></div>}
  </div>
}
